1. Loading and Understanding the Dataset

In [2]:
#Question 1
#Import the Pandas library using the alias pd and read PimaIndiansDiabetes.csv into a DataFrame named df.
import pandas as pd
path = "https://raw.githubusercontent.com/hakimyameen/Data-Science-Assignments/refs/heads/main/Assignment%202/PimaIndiansDiabetes.csv"

df=pd.read_csv(path)
print(df)

     TimesPregnant  GlucoseConcentration  BloodPrs  SkinThickness  Serum  \
0                6                   148        72             35      0
1                1                    85        66             29      0
2                8                   183        64              0      0
3                1                    89        66             23     94
4                0                   137        40             35    168
..             ...                   ...       ...            ...    ...
763             10                   101        76             48    180
764              2                   122        70             27      0
765              5                   121        72             23    112
766              1                   126        60              0      0
767              1                    93        70             31      0

      BMI  DiabetesFunct  Age  Class
0    33.6          0.627   50      1
1    26.6          0.351   31      0
2    23.3          0.672   32      1
3    28.1          0.167   21      0
4    43.1          2.288   33      1
..    ...            ...  ...    ...
763  32.9          0.171   63      0
764  36.8          0.340   27      0
765  26.2          0.245   30      0
766  30.1          0.349   47      1
767  30.4          0.315   23      0

[768 rows x 9 columns]

In [3]:
#Question 2
#Display the first 5 rows of the dataset.
df.head(5)

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
#Question 3
#Display the last 5 rows of the dataset.
df.tail(5)

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [6]:
#Question 4
#Find the total number of rows and columns in the dataset.
df.shape

(768, 9)

In [9]:
#Question 5
#Display all the column names in the dataset.
df.columns

Index(['TimesPregnant', 'GlucoseConcentration', 'BloodPrs', 'SkinThickness',
       'Serum', 'BMI', 'DiabetesFunct', 'Age', 'Class'],
      dtype='str')

In [10]:
#Question 6
#Display the data type of each column.
df.dtypes

TimesPregnant             int64
GlucoseConcentration      int64
BloodPrs                  int64
SkinThickness             int64
Serum                     int64
BMI                     float64
DiabetesFunct           float64
Age                       int64
Class                     int64
dtype: object

In [11]:
#Question 7
#Display complete information about the DataFrame using info().
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TimesPregnant         768 non-null    int64
 1   GlucoseConcentration  768 non-null    int64
 2   BloodPrs              768 non-null    int64
 3   SkinThickness         768 non-null    int64
 4   Serum                 768 non-null    int64
 5   BMI                   768 non-null    float64
 6   DiabetesFunct         768 non-null    float64
 7   Age                   768 non-null    int64
 8   Class                 768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

2. Checking Missing Values

In [13]:
#Question 8
#Check the number of null values in each column using isnull().
df.isnull().sum()

TimesPregnant           0
GlucoseConcentration    0
BloodPrs                0
SkinThickness           0
Serum                   0
BMI                     0
DiabetesFunct           0
Age                     0
Class                   0
dtype: int64

In [14]:
#Question 9
#Check the missing values again using isna().
df.isna()

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False

3. Selecting Data

In [15]:
#Question 10
#Select and display only the Age column.
df['Age']

0      50
1      31
2      32
3      21
4      33
       ..
763    63
764    27
765    30
766    47
767    23
Name: Age, Length: 768, dtype: int64

In [17]:
#Question 11
#Select and display the Age, BMI, and Class columns.
df[['Age','BMI','Class']]

     Age   BMI  Class
0     50  33.6      1
1     31  26.6      0
2     32  23.3      1
3     21  28.1      0
4     33  43.1      1
..   ...   ...    ...
763   63  32.9      0
764   27  36.8      0
765   30  26.2      0
766   47  30.1      1
767   23  30.4      0

[768 rows x 3 columns]

In [18]:
#Question 12
#Display the first 10 rows using DataFrame slicing.
df[0:10]

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [20]:
#Question 13
#Using iloc, display the first 5 rows and first 4 columns.
df.iloc[0:5 , 0:4]

   TimesPregnant  GlucoseConcentration  BloodPrs  SkinThickness
0              6                   148        72             35
1              1                    85        66             29
2              8                   183        64              0
3              1                    89        66             23
4              0                   137        40             35

In [21]:
#Question 14
#Using loc, display rows 0 to 5 for the columns GlucoseConcentration, BMI, and Age.
df.loc[0:5,["GlucoseConcentration","Age","BMI"]]

   GlucoseConcentration  Age   BMI
0                   148   50  33.6
1                    85   31  26.6
2                   183   32  23.3
3                    89   21  28.1
4                   137   33  43.1
5                   116   30  25.6

4. Understanding Values

In [23]:
#Question 15
#Display all the unique values available in the Class column.
df['Class'].unique()

array([1, 0])

In [24]:
#Question 16
#Find the number of unique values in the Class column.
df['Class'].nunique()

2

In [26]:
#Question 17
#Count how many records belong to Class 0 and Class 1 using value_counts().
df['Class'].value_counts()

Class
0    500
1    268
Name: count, dtype: int64

In [27]:
#Question 18
#Find the number of unique ages present in the dataset.
df['Age'].nunique()

52

5. Basic Analysis

In [28]:
#Question 19
#Find the maximum age in the dataset.
df['Age'].max()

np.int64(81)

In [31]:
#Question 20
#Find the maximum glucose concentration in the dataset.
df['GlucoseConcentration'].max()

np.int64(199)

In [34]:
#Question 21
#Find the maximum BMI in the dataset.
df['BMI'].max()

np.float64(67.1)

In [35]:
#Question 22
#Find the minimum age in the dataset.
df['Age'].min()

np.int64(21)

6. Filtering Records

In [38]:
#Question 23
#Display all records where Age is greater than 40.
df.query('Age > 40')

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
763,10,101,76,48,180,32.9,0.171,63,0
766,1,126,60,0,0,30.1,0.349,47,1

In [39]:
#Question 24
#Display all records where BMI is greater than 30.
df.query('BMI > 30')

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
761,9,170,74,31,0,44.0,0.403,43,1
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [40]:
#Question 25
#Display all records where TimesPregnant is greater than 5.
df.query('TimesPregnant > 5')

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
7,10,115,0,0,0,35.3,0.134,29,0
9,8,125,96,0,0,0.0,0.232,54,1
11,10,168,74,0,0,38.0,0.537,34,1
...,...,...,...,...,...,...,...,...,...
756,7,137,90,41,0,32.0,0.391,39,0
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0

In [42]:
#Question 26
#Display only the records where Class is equal to 1.
df.query('Class == 1')

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [43]:
#Question 27
#Using query(), display all records where Age is greater than 50.
df.query('Age > 50')

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76,27,0,35.6,0.378,52,1
734,2,105,75,0,0,23.3,0.560,53,0
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

In [44]:
#Question 28
#Using query(), display all records where BMI is greater than 30 and Class is equal to 1.
df.query('BMI > 30' and 'Class == 1')

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

7. Creating and Modifying Columns

In [46]:
#Question 29
#Create a new column named AgeGroup. Store Above 40 when Age is greater than 40; otherwise store 40 or Below. Use apply() with a lambda function.
df['AgeGroup']=df['Age'].apply(lambda x: 'Above 40' if x > 40 else ' 40 or Below ')
df

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class,AgeGroup
0,6,148,72,35,0,33.6,0.627,50,1,Above 40
1,1,85,66,29,0,26.6,0.351,31,0,40 or Below
2,8,183,64,0,0,23.3,0.672,32,1,40 or Below
3,1,89,66,23,94,28.1,0.167,21,0,40 or Below
4,0,137,40,35,168,43.1,2.288,33,1,40 or Below
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,Above 40
764,2,122,70,27,0,36.8,0.340,27,0,40 or Below
765,5,121,72,23,112,26.2,0.245,30,0,40 or Below
766,1,126,60,0,0,30.1,0.349,47,1,Above 40
767,1,93,70,31,0,30.4,0.315,23,0,40 or Below

In [47]:
#Question 30
#Display the first 10 rows after creating the AgeGroup column.
df.head(10)

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class,AgeGroup
0,6,148,72,35,0,33.6,0.627,50,1,Above 40
1,1,85,66,29,0,26.6,0.351,31,0,40 or Below
2,8,183,64,0,0,23.3,0.672,32,1,40 or Below
3,1,89,66,23,94,28.1,0.167,21,0,40 or Below
4,0,137,40,35,168,43.1,2.288,33,1,40 or Below
5,5,116,74,0,0,25.6,0.201,30,0,40 or Below
6,3,78,50,32,88,31.0,0.248,26,1,40 or Below
7,10,115,0,0,0,35.3,0.134,29,0,40 or Below
8,2,197,70,45,543,30.5,0.158,53,1,Above 40
9,8,125,96,0,0,0.0,0.232,54,1,Above 40

In [48]:
#Question 31
#Count the values in the newly created AgeGroup column using value_counts().
df['AgeGroup'].value_counts()

AgeGroup
 40 or Below     574
Above 40         194
Name: count, dtype: int64

In [53]:
#Question 32
#Remove the AgeGroup column using drop().
df.drop(columns=['AgeGroup'], inplace=True)

In [56]:
#Question 33
#Rename the column BloodPrs to BloodPressure.
df.rename(columns={'Bloodprs':'BloodPressure'},inplace=True)
df

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

8. Conversion and Export

In [59]:
#Question 34
#Select and display only the numeric columns using select_dtypes().
df.select_dtypes(include=['number'])

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [64]:
#Question 35
#Convert the first 10 rows of the DataFrame into a NumPy array using to_numpy().
df[0:10].to_numpy()

array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01, 1.000e+00],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01, 0.000e+00],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01, 1.000e+00],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01, 0.000e+00],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01, 1.000e+00],
       [5.000e+00, 1.160e+02, 7.400e+01, 0.000e+00, 0.000e+00, 2.560e+01,
        2.010e-01, 3.000e+01, 0.000e+00],
       [3.000e+00, 7.800e+01, 5.000e+01, 3.200e+01, 8.800e+01, 3.100e+01,
        2.480e-01, 2.600e+01, 1.000e+00],
       [1.000e+01, 1.150e+02, 0.000e+00, 0.000e+00, 0.000e+00, 3.530e+01,
        1.340e-01, 2.900e+01, 0.000e+00],
       [2.000e+00, 1.970e+02, 7.000e+01, 4.500e+01, 5.430e+02, 3.050e+01,
        1.580e-01, 5.300e+01, 1.000e+00],
       [8.000e+00, 1.250e+02, 9.600e+01, 0.000e+00, 0.000e+00, 0.000e+00,
        2.320e-01, 5.400e+01, 1.000e+00]])

In [65]:
#Question 36
#Save the DataFrame as a new CSV file named Pima_Diabetes_Practice_Output.csv without saving the index.
df.to_csv("Pima_Diabetes_Practice_Output.csv",index=False)